package com.qm.laoxiang.domain.db;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hometown
 *
 * @mbg.generated do_not_delete_during_merge Sun Dec 23 19:33:53 CST 2018
 */
public class Hometown {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hometown.id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hometown.level
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hometown.name
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hometown.created
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hometown.modified
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hometown.yn
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Integer yn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hometown.id
     *
     * @return the value of hometown.id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hometown.id
     *
     * @param id the value for hometown.id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hometown.level
     *
     * @return the value of hometown.level
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hometown.level
     *
     * @param level the value for hometown.level
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hometown.name
     *
     * @return the value of hometown.name
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hometown.name
     *
     * @param name the value for hometown.name
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hometown.created
     *
     * @return the value of hometown.created
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hometown.created
     *
     * @param created the value for hometown.created
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hometown.modified
     *
     * @return the value of hometown.modified
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hometown.modified
     *
     * @param modified the value for hometown.modified
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hometown.yn
     *
     * @return the value of hometown.yn
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Integer getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hometown.yn
     *
     * @param yn the value for hometown.yn
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setYn(Integer yn) {
        this.yn = yn;
    }
}