package com.qm.laoxiang.domain.db;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table post_info
 *
 * @mbg.generated do_not_delete_during_merge Sun Jan 27 23:02:56 CST 2019
 */
public class PostInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_info.id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_info.title
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_info.content
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_info.show_durtion
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer showDurtion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_info.created
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_info.modified
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_info.usr_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Long usrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_info.visit_cnt
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer visitCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_info.praise_cnt
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer praiseCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_info.top
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer top;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_info.yn
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_info.region_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_info.hometown_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer hometownId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_info.id
     *
     * @return the value of post_info.id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_info.id
     *
     * @param id the value for post_info.id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_info.title
     *
     * @return the value of post_info.title
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_info.title
     *
     * @param title the value for post_info.title
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_info.content
     *
     * @return the value of post_info.content
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_info.content
     *
     * @param content the value for post_info.content
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_info.show_durtion
     *
     * @return the value of post_info.show_durtion
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getShowDurtion() {
        return showDurtion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_info.show_durtion
     *
     * @param showDurtion the value for post_info.show_durtion
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setShowDurtion(Integer showDurtion) {
        this.showDurtion = showDurtion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_info.created
     *
     * @return the value of post_info.created
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_info.created
     *
     * @param created the value for post_info.created
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_info.modified
     *
     * @return the value of post_info.modified
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_info.modified
     *
     * @param modified the value for post_info.modified
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_info.usr_id
     *
     * @return the value of post_info.usr_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Long getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_info.usr_id
     *
     * @param usrId the value for post_info.usr_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setUsrId(Long usrId) {
        this.usrId = usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_info.visit_cnt
     *
     * @return the value of post_info.visit_cnt
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getVisitCnt() {
        return visitCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_info.visit_cnt
     *
     * @param visitCnt the value for post_info.visit_cnt
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setVisitCnt(Integer visitCnt) {
        this.visitCnt = visitCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_info.praise_cnt
     *
     * @return the value of post_info.praise_cnt
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getPraiseCnt() {
        return praiseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_info.praise_cnt
     *
     * @param praiseCnt the value for post_info.praise_cnt
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setPraiseCnt(Integer praiseCnt) {
        this.praiseCnt = praiseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_info.top
     *
     * @return the value of post_info.top
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_info.top
     *
     * @param top the value for post_info.top
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setTop(Integer top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_info.yn
     *
     * @return the value of post_info.yn
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_info.yn
     *
     * @param yn the value for post_info.yn
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setYn(Integer yn) {
        this.yn = yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_info.region_id
     *
     * @return the value of post_info.region_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_info.region_id
     *
     * @param regionId the value for post_info.region_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_info.hometown_id
     *
     * @return the value of post_info.hometown_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getHometownId() {
        return hometownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_info.hometown_id
     *
     * @param hometownId the value for post_info.hometown_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setHometownId(Integer hometownId) {
        this.hometownId = hometownId;
    }
}