package com.qm.laoxiang.domain.db;

import java.util.ArrayList;
import java.util.List;

public class QrInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public QrInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andQrUrlIsNull() {
            addCriterion("qr_url is null");
            return (Criteria) this;
        }

        public Criteria andQrUrlIsNotNull() {
            addCriterion("qr_url is not null");
            return (Criteria) this;
        }

        public Criteria andQrUrlEqualTo(String value) {
            addCriterion("qr_url =", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlNotEqualTo(String value) {
            addCriterion("qr_url <>", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlGreaterThan(String value) {
            addCriterion("qr_url >", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlGreaterThanOrEqualTo(String value) {
            addCriterion("qr_url >=", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlLessThan(String value) {
            addCriterion("qr_url <", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlLessThanOrEqualTo(String value) {
            addCriterion("qr_url <=", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlLike(String value) {
            addCriterion("qr_url like", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlNotLike(String value) {
            addCriterion("qr_url not like", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlIn(List<String> values) {
            addCriterion("qr_url in", values, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlNotIn(List<String> values) {
            addCriterion("qr_url not in", values, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlBetween(String value1, String value2) {
            addCriterion("qr_url between", value1, value2, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlNotBetween(String value1, String value2) {
            addCriterion("qr_url not between", value1, value2, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andOwnerWxIsNull() {
            addCriterion("owner_wx is null");
            return (Criteria) this;
        }

        public Criteria andOwnerWxIsNotNull() {
            addCriterion("owner_wx is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerWxEqualTo(String value) {
            addCriterion("owner_wx =", value, "ownerWx");
            return (Criteria) this;
        }

        public Criteria andOwnerWxNotEqualTo(String value) {
            addCriterion("owner_wx <>", value, "ownerWx");
            return (Criteria) this;
        }

        public Criteria andOwnerWxGreaterThan(String value) {
            addCriterion("owner_wx >", value, "ownerWx");
            return (Criteria) this;
        }

        public Criteria andOwnerWxGreaterThanOrEqualTo(String value) {
            addCriterion("owner_wx >=", value, "ownerWx");
            return (Criteria) this;
        }

        public Criteria andOwnerWxLessThan(String value) {
            addCriterion("owner_wx <", value, "ownerWx");
            return (Criteria) this;
        }

        public Criteria andOwnerWxLessThanOrEqualTo(String value) {
            addCriterion("owner_wx <=", value, "ownerWx");
            return (Criteria) this;
        }

        public Criteria andOwnerWxLike(String value) {
            addCriterion("owner_wx like", value, "ownerWx");
            return (Criteria) this;
        }

        public Criteria andOwnerWxNotLike(String value) {
            addCriterion("owner_wx not like", value, "ownerWx");
            return (Criteria) this;
        }

        public Criteria andOwnerWxIn(List<String> values) {
            addCriterion("owner_wx in", values, "ownerWx");
            return (Criteria) this;
        }

        public Criteria andOwnerWxNotIn(List<String> values) {
            addCriterion("owner_wx not in", values, "ownerWx");
            return (Criteria) this;
        }

        public Criteria andOwnerWxBetween(String value1, String value2) {
            addCriterion("owner_wx between", value1, value2, "ownerWx");
            return (Criteria) this;
        }

        public Criteria andOwnerWxNotBetween(String value1, String value2) {
            addCriterion("owner_wx not between", value1, value2, "ownerWx");
            return (Criteria) this;
        }

        public Criteria andRegionHometownIdIsNull() {
            addCriterion("region_hometown_id is null");
            return (Criteria) this;
        }

        public Criteria andRegionHometownIdIsNotNull() {
            addCriterion("region_hometown_id is not null");
            return (Criteria) this;
        }

        public Criteria andRegionHometownIdEqualTo(Long value) {
            addCriterion("region_hometown_id =", value, "regionHometownId");
            return (Criteria) this;
        }

        public Criteria andRegionHometownIdNotEqualTo(Long value) {
            addCriterion("region_hometown_id <>", value, "regionHometownId");
            return (Criteria) this;
        }

        public Criteria andRegionHometownIdGreaterThan(Long value) {
            addCriterion("region_hometown_id >", value, "regionHometownId");
            return (Criteria) this;
        }

        public Criteria andRegionHometownIdGreaterThanOrEqualTo(Long value) {
            addCriterion("region_hometown_id >=", value, "regionHometownId");
            return (Criteria) this;
        }

        public Criteria andRegionHometownIdLessThan(Long value) {
            addCriterion("region_hometown_id <", value, "regionHometownId");
            return (Criteria) this;
        }

        public Criteria andRegionHometownIdLessThanOrEqualTo(Long value) {
            addCriterion("region_hometown_id <=", value, "regionHometownId");
            return (Criteria) this;
        }

        public Criteria andRegionHometownIdIn(List<Long> values) {
            addCriterion("region_hometown_id in", values, "regionHometownId");
            return (Criteria) this;
        }

        public Criteria andRegionHometownIdNotIn(List<Long> values) {
            addCriterion("region_hometown_id not in", values, "regionHometownId");
            return (Criteria) this;
        }

        public Criteria andRegionHometownIdBetween(Long value1, Long value2) {
            addCriterion("region_hometown_id between", value1, value2, "regionHometownId");
            return (Criteria) this;
        }

        public Criteria andRegionHometownIdNotBetween(Long value1, Long value2) {
            addCriterion("region_hometown_id not between", value1, value2, "regionHometownId");
            return (Criteria) this;
        }

        public Criteria andUsrIdIsNull() {
            addCriterion("usr_id is null");
            return (Criteria) this;
        }

        public Criteria andUsrIdIsNotNull() {
            addCriterion("usr_id is not null");
            return (Criteria) this;
        }

        public Criteria andUsrIdEqualTo(Long value) {
            addCriterion("usr_id =", value, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdNotEqualTo(Long value) {
            addCriterion("usr_id <>", value, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdGreaterThan(Long value) {
            addCriterion("usr_id >", value, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdGreaterThanOrEqualTo(Long value) {
            addCriterion("usr_id >=", value, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdLessThan(Long value) {
            addCriterion("usr_id <", value, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdLessThanOrEqualTo(Long value) {
            addCriterion("usr_id <=", value, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdIn(List<Long> values) {
            addCriterion("usr_id in", values, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdNotIn(List<Long> values) {
            addCriterion("usr_id not in", values, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdBetween(Long value1, Long value2) {
            addCriterion("usr_id between", value1, value2, "usrId");
            return (Criteria) this;
        }

        public Criteria andUsrIdNotBetween(Long value1, Long value2) {
            addCriterion("usr_id not between", value1, value2, "usrId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qr_info
     *
     * @mbg.generated do_not_delete_during_merge Sun Dec 23 19:33:53 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qr_info
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}