package com.qm.laoxiang.domain.db;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table region_hometown_link
 *
 * @mbg.generated do_not_delete_during_merge Sun Dec 23 19:33:53 CST 2018
 */
public class RegionHometownLink {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_hometown_link.id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_hometown_link.regionId
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Integer regionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_hometown_link.hometownId
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Integer hometownid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_hometown_link.yn
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Integer yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_hometown_link.created
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_hometown_link.modified
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Date modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_hometown_link.id
     *
     * @return the value of region_hometown_link.id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_hometown_link.id
     *
     * @param id the value for region_hometown_link.id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_hometown_link.regionId
     *
     * @return the value of region_hometown_link.regionId
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Integer getRegionid() {
        return regionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_hometown_link.regionId
     *
     * @param regionid the value for region_hometown_link.regionId
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setRegionid(Integer regionid) {
        this.regionid = regionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_hometown_link.hometownId
     *
     * @return the value of region_hometown_link.hometownId
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Integer getHometownid() {
        return hometownid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_hometown_link.hometownId
     *
     * @param hometownid the value for region_hometown_link.hometownId
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setHometownid(Integer hometownid) {
        this.hometownid = hometownid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_hometown_link.yn
     *
     * @return the value of region_hometown_link.yn
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Integer getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_hometown_link.yn
     *
     * @param yn the value for region_hometown_link.yn
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setYn(Integer yn) {
        this.yn = yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_hometown_link.created
     *
     * @return the value of region_hometown_link.created
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_hometown_link.created
     *
     * @param created the value for region_hometown_link.created
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_hometown_link.modified
     *
     * @return the value of region_hometown_link.modified
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_hometown_link.modified
     *
     * @param modified the value for region_hometown_link.modified
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }
}