package com.qm.laoxiang.domain.db;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table region
 *
 * @mbg.generated do_not_delete_during_merge Sun Jan 27 23:02:56 CST 2019
 */
public class Region {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.level
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.name
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.yn
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.created
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.modified
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Date modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.id
     *
     * @return the value of region.id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.id
     *
     * @param id the value for region.id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.level
     *
     * @return the value of region.level
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.level
     *
     * @param level the value for region.level
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.name
     *
     * @return the value of region.name
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.name
     *
     * @param name the value for region.name
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.yn
     *
     * @return the value of region.yn
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.yn
     *
     * @param yn the value for region.yn
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setYn(Integer yn) {
        this.yn = yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.created
     *
     * @return the value of region.created
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.created
     *
     * @param created the value for region.created
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.modified
     *
     * @return the value of region.modified
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.modified
     *
     * @param modified the value for region.modified
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }
}