package com.qm.laoxiang.domain.db;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table reply_info
 *
 * @mbg.generated do_not_delete_during_merge Sun Jan 27 23:02:56 CST 2019
 */
public class ReplyInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.content
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.usr_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Long usrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.region_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.hometown_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer hometownId;

    /**
     * Database Column Remarks:
     *   回复的最顶级回复id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.reply_parent_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Long replyParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.praise_cnt
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer praiseCnt;

    /**
     * Database Column Remarks:
     *   回复的上一级回复id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.reply_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Long replyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.post_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Long postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.top
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer top;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.created
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.modified
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.yn
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer yn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.id
     *
     * @return the value of reply_info.id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.id
     *
     * @param id the value for reply_info.id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.content
     *
     * @return the value of reply_info.content
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.content
     *
     * @param content the value for reply_info.content
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.usr_id
     *
     * @return the value of reply_info.usr_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Long getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.usr_id
     *
     * @param usrId the value for reply_info.usr_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setUsrId(Long usrId) {
        this.usrId = usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.region_id
     *
     * @return the value of reply_info.region_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.region_id
     *
     * @param regionId the value for reply_info.region_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.hometown_id
     *
     * @return the value of reply_info.hometown_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getHometownId() {
        return hometownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.hometown_id
     *
     * @param hometownId the value for reply_info.hometown_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setHometownId(Integer hometownId) {
        this.hometownId = hometownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.reply_parent_id
     *
     * @return the value of reply_info.reply_parent_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Long getReplyParentId() {
        return replyParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.reply_parent_id
     *
     * @param replyParentId the value for reply_info.reply_parent_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setReplyParentId(Long replyParentId) {
        this.replyParentId = replyParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.praise_cnt
     *
     * @return the value of reply_info.praise_cnt
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getPraiseCnt() {
        return praiseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.praise_cnt
     *
     * @param praiseCnt the value for reply_info.praise_cnt
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setPraiseCnt(Integer praiseCnt) {
        this.praiseCnt = praiseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.reply_id
     *
     * @return the value of reply_info.reply_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Long getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.reply_id
     *
     * @param replyId the value for reply_info.reply_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setReplyId(Long replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.post_id
     *
     * @return the value of reply_info.post_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.post_id
     *
     * @param postId the value for reply_info.post_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.top
     *
     * @return the value of reply_info.top
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.top
     *
     * @param top the value for reply_info.top
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setTop(Integer top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.created
     *
     * @return the value of reply_info.created
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.created
     *
     * @param created the value for reply_info.created
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.modified
     *
     * @return the value of reply_info.modified
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.modified
     *
     * @param modified the value for reply_info.modified
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.yn
     *
     * @return the value of reply_info.yn
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.yn
     *
     * @param yn the value for reply_info.yn
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setYn(Integer yn) {
        this.yn = yn;
    }
}