package com.qm.laoxiang.domain.db;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table reply_info
 *
 * @mbg.generated do_not_delete_during_merge Sun Dec 23 19:33:53 CST 2018
 */
public class ReplyInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.content
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.post_author
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Integer postAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.usr_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Long usrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.region_hometown_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Integer regionHometownId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.reply_parent_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Long replyParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.praise_cnt
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Integer praiseCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.reply_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Long replyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.post_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Long postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.top
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Integer top;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.created
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private String created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.modified
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private String modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_info.yn
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Integer yn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.id
     *
     * @return the value of reply_info.id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.id
     *
     * @param id the value for reply_info.id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.content
     *
     * @return the value of reply_info.content
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.content
     *
     * @param content the value for reply_info.content
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.post_author
     *
     * @return the value of reply_info.post_author
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Integer getPostAuthor() {
        return postAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.post_author
     *
     * @param postAuthor the value for reply_info.post_author
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setPostAuthor(Integer postAuthor) {
        this.postAuthor = postAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.usr_id
     *
     * @return the value of reply_info.usr_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Long getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.usr_id
     *
     * @param usrId the value for reply_info.usr_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setUsrId(Long usrId) {
        this.usrId = usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.region_hometown_id
     *
     * @return the value of reply_info.region_hometown_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Integer getRegionHometownId() {
        return regionHometownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.region_hometown_id
     *
     * @param regionHometownId the value for reply_info.region_hometown_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setRegionHometownId(Integer regionHometownId) {
        this.regionHometownId = regionHometownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.reply_parent_id
     *
     * @return the value of reply_info.reply_parent_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Long getReplyParentId() {
        return replyParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.reply_parent_id
     *
     * @param replyParentId the value for reply_info.reply_parent_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setReplyParentId(Long replyParentId) {
        this.replyParentId = replyParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.praise_cnt
     *
     * @return the value of reply_info.praise_cnt
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Integer getPraiseCnt() {
        return praiseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.praise_cnt
     *
     * @param praiseCnt the value for reply_info.praise_cnt
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setPraiseCnt(Integer praiseCnt) {
        this.praiseCnt = praiseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.reply_id
     *
     * @return the value of reply_info.reply_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Long getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.reply_id
     *
     * @param replyId the value for reply_info.reply_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setReplyId(Long replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.post_id
     *
     * @return the value of reply_info.post_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.post_id
     *
     * @param postId the value for reply_info.post_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.top
     *
     * @return the value of reply_info.top
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Integer getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.top
     *
     * @param top the value for reply_info.top
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setTop(Integer top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.created
     *
     * @return the value of reply_info.created
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.created
     *
     * @param created the value for reply_info.created
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setCreated(String created) {
        this.created = created == null ? null : created.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.modified
     *
     * @return the value of reply_info.modified
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.modified
     *
     * @param modified the value for reply_info.modified
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setModified(String modified) {
        this.modified = modified == null ? null : modified.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_info.yn
     *
     * @return the value of reply_info.yn
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Integer getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_info.yn
     *
     * @param yn the value for reply_info.yn
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setYn(Integer yn) {
        this.yn = yn;
    }
}