package com.qm.laoxiang.domain.db;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 *
 * @mbg.generated do_not_delete_during_merge Sun Dec 23 19:33:53 CST 2018
 */
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.real_name
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.national_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private String nationalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wx_openid
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private String wxOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wx_nickname
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private String wxNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wx_avatar
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private String wxAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wx_age
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private String wxAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wx_gender
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private String wxGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wx_country
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private String wxCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wx_province
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private String wxProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wx_city
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private String wxCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.yn
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Integer yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.modified
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Date modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.real_name
     *
     * @return the value of user.real_name
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.real_name
     *
     * @param realName the value for user.real_name
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.national_id
     *
     * @return the value of user.national_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getNationalId() {
        return nationalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.national_id
     *
     * @param nationalId the value for user.national_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setNationalId(String nationalId) {
        this.nationalId = nationalId == null ? null : nationalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wx_openid
     *
     * @return the value of user.wx_openid
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wx_openid
     *
     * @param wxOpenid the value for user.wx_openid
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid == null ? null : wxOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wx_nickname
     *
     * @return the value of user.wx_nickname
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getWxNickname() {
        return wxNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wx_nickname
     *
     * @param wxNickname the value for user.wx_nickname
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setWxNickname(String wxNickname) {
        this.wxNickname = wxNickname == null ? null : wxNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wx_avatar
     *
     * @return the value of user.wx_avatar
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getWxAvatar() {
        return wxAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wx_avatar
     *
     * @param wxAvatar the value for user.wx_avatar
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setWxAvatar(String wxAvatar) {
        this.wxAvatar = wxAvatar == null ? null : wxAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wx_age
     *
     * @return the value of user.wx_age
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getWxAge() {
        return wxAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wx_age
     *
     * @param wxAge the value for user.wx_age
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setWxAge(String wxAge) {
        this.wxAge = wxAge == null ? null : wxAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wx_gender
     *
     * @return the value of user.wx_gender
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getWxGender() {
        return wxGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wx_gender
     *
     * @param wxGender the value for user.wx_gender
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setWxGender(String wxGender) {
        this.wxGender = wxGender == null ? null : wxGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wx_country
     *
     * @return the value of user.wx_country
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getWxCountry() {
        return wxCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wx_country
     *
     * @param wxCountry the value for user.wx_country
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setWxCountry(String wxCountry) {
        this.wxCountry = wxCountry == null ? null : wxCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wx_province
     *
     * @return the value of user.wx_province
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getWxProvince() {
        return wxProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wx_province
     *
     * @param wxProvince the value for user.wx_province
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setWxProvince(String wxProvince) {
        this.wxProvince = wxProvince == null ? null : wxProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wx_city
     *
     * @return the value of user.wx_city
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public String getWxCity() {
        return wxCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wx_city
     *
     * @param wxCity the value for user.wx_city
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setWxCity(String wxCity) {
        this.wxCity = wxCity == null ? null : wxCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.yn
     *
     * @return the value of user.yn
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Integer getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.yn
     *
     * @param yn the value for user.yn
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setYn(Integer yn) {
        this.yn = yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created
     *
     * @return the value of user.created
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created
     *
     * @param created the value for user.created
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.modified
     *
     * @return the value of user.modified
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.modified
     *
     * @param modified the value for user.modified
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }
}