package com.qm.laoxiang.domain.db;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table usr_region_hometown_link
 *
 * @mbg.generated do_not_delete_during_merge Sun Dec 23 19:33:53 CST 2018
 */
public class UsrRegionHometownLink {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_region_hometown_link.id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_region_hometown_link.usr_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Long usrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_region_hometown_link.region_hometown_link_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Long regionHometownLinkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_region_hometown_link.created
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_region_hometown_link.modified
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_region_hometown_link.yn
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    private Date yn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_region_hometown_link.id
     *
     * @return the value of usr_region_hometown_link.id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_region_hometown_link.id
     *
     * @param id the value for usr_region_hometown_link.id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_region_hometown_link.usr_id
     *
     * @return the value of usr_region_hometown_link.usr_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Long getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_region_hometown_link.usr_id
     *
     * @param usrId the value for usr_region_hometown_link.usr_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setUsrId(Long usrId) {
        this.usrId = usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_region_hometown_link.region_hometown_link_id
     *
     * @return the value of usr_region_hometown_link.region_hometown_link_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Long getRegionHometownLinkId() {
        return regionHometownLinkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_region_hometown_link.region_hometown_link_id
     *
     * @param regionHometownLinkId the value for usr_region_hometown_link.region_hometown_link_id
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setRegionHometownLinkId(Long regionHometownLinkId) {
        this.regionHometownLinkId = regionHometownLinkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_region_hometown_link.created
     *
     * @return the value of usr_region_hometown_link.created
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_region_hometown_link.created
     *
     * @param created the value for usr_region_hometown_link.created
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_region_hometown_link.modified
     *
     * @return the value of usr_region_hometown_link.modified
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_region_hometown_link.modified
     *
     * @param modified the value for usr_region_hometown_link.modified
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_region_hometown_link.yn
     *
     * @return the value of usr_region_hometown_link.yn
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public Date getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_region_hometown_link.yn
     *
     * @param yn the value for usr_region_hometown_link.yn
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    public void setYn(Date yn) {
        this.yn = yn;
    }
}