package com.qm.laoxiang.domain.db;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table usr_region_hometown_link
 *
 * @mbg.generated do_not_delete_during_merge Sun Jan 27 23:02:56 CST 2019
 */
public class UsrRegionHometownLink {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_region_hometown_link.id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_region_hometown_link.usr_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Long usrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_region_hometown_link.hometown_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer hometownId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_region_hometown_link.region_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_region_hometown_link.created
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_region_hometown_link.modified
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_region_hometown_link.yn
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    private Integer yn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_region_hometown_link.id
     *
     * @return the value of usr_region_hometown_link.id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_region_hometown_link.id
     *
     * @param id the value for usr_region_hometown_link.id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_region_hometown_link.usr_id
     *
     * @return the value of usr_region_hometown_link.usr_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Long getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_region_hometown_link.usr_id
     *
     * @param usrId the value for usr_region_hometown_link.usr_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setUsrId(Long usrId) {
        this.usrId = usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_region_hometown_link.hometown_id
     *
     * @return the value of usr_region_hometown_link.hometown_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getHometownId() {
        return hometownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_region_hometown_link.hometown_id
     *
     * @param hometownId the value for usr_region_hometown_link.hometown_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setHometownId(Integer hometownId) {
        this.hometownId = hometownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_region_hometown_link.region_id
     *
     * @return the value of usr_region_hometown_link.region_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_region_hometown_link.region_id
     *
     * @param regionId the value for usr_region_hometown_link.region_id
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_region_hometown_link.created
     *
     * @return the value of usr_region_hometown_link.created
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_region_hometown_link.created
     *
     * @param created the value for usr_region_hometown_link.created
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_region_hometown_link.modified
     *
     * @return the value of usr_region_hometown_link.modified
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_region_hometown_link.modified
     *
     * @param modified the value for usr_region_hometown_link.modified
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_region_hometown_link.yn
     *
     * @return the value of usr_region_hometown_link.yn
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public Integer getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_region_hometown_link.yn
     *
     * @param yn the value for usr_region_hometown_link.yn
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    public void setYn(Integer yn) {
        this.yn = yn;
    }
}