package com.qm.laoxiang.dao.mapper;

import com.qm.laoxiang.domain.db.Hometown;
import com.qm.laoxiang.domain.db.HometownExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HometownMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hometown
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    long countByExample(HometownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hometown
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int deleteByExample(HometownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hometown
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hometown
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int insert(Hometown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hometown
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int insertSelective(Hometown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hometown
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    List<Hometown> selectByExample(HometownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hometown
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    Hometown selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hometown
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") Hometown record, @Param("example") HometownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hometown
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int updateByExample(@Param("record") Hometown record, @Param("example") HometownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hometown
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int updateByPrimaryKeySelective(Hometown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hometown
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int updateByPrimaryKey(Hometown record);
}