package com.qm.laoxiang.dao.mapper;

import com.qm.laoxiang.domain.db.PostInfo;
import com.qm.laoxiang.domain.db.PostInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    long countByExample(PostInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int deleteByExample(PostInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int insert(PostInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int insertSelective(PostInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    List<PostInfo> selectByExample(PostInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    PostInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") PostInfo record, @Param("example") PostInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int updateByExample(@Param("record") PostInfo record, @Param("example") PostInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int updateByPrimaryKeySelective(PostInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int updateByPrimaryKey(PostInfo record);
}