package com.qm.laoxiang.dao.mapper;

import com.qm.laoxiang.domain.db.QrDownload;
import com.qm.laoxiang.domain.db.QrDownloadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrDownloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_download
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    long countByExample(QrDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_download
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int deleteByExample(QrDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_download
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_download
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int insert(QrDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_download
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int insertSelective(QrDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_download
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    List<QrDownload> selectByExample(QrDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_download
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    QrDownload selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_download
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") QrDownload record, @Param("example") QrDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_download
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int updateByExample(@Param("record") QrDownload record, @Param("example") QrDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_download
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int updateByPrimaryKeySelective(QrDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_download
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int updateByPrimaryKey(QrDownload record);
}