package com.qm.laoxiang.dao.mapper;

import com.qm.laoxiang.domain.db.QrInfo;
import com.qm.laoxiang.domain.db.QrInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    long countByExample(QrInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int deleteByExample(QrInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int insert(QrInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int insertSelective(QrInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    List<QrInfo> selectByExample(QrInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    QrInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") QrInfo record, @Param("example") QrInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int updateByExample(@Param("record") QrInfo record, @Param("example") QrInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int updateByPrimaryKeySelective(QrInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_info
     *
     * @mbg.generated Sun Jan 27 23:02:56 CST 2019
     */
    int updateByPrimaryKey(QrInfo record);
}