package com.qm.laoxiang.dao.mapper;

import com.qm.laoxiang.domain.db.UsrRegionHometownLink;
import com.qm.laoxiang.domain.db.UsrRegionHometownLinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsrRegionHometownLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_region_hometown_link
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    long countByExample(UsrRegionHometownLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_region_hometown_link
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int deleteByExample(UsrRegionHometownLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_region_hometown_link
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_region_hometown_link
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int insert(UsrRegionHometownLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_region_hometown_link
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int insertSelective(UsrRegionHometownLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_region_hometown_link
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    List<UsrRegionHometownLink> selectByExample(UsrRegionHometownLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_region_hometown_link
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    UsrRegionHometownLink selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_region_hometown_link
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") UsrRegionHometownLink record, @Param("example") UsrRegionHometownLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_region_hometown_link
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int updateByExample(@Param("record") UsrRegionHometownLink record, @Param("example") UsrRegionHometownLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_region_hometown_link
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int updateByPrimaryKeySelective(UsrRegionHometownLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_region_hometown_link
     *
     * @mbg.generated Sun Dec 23 19:33:53 CST 2018
     */
    int updateByPrimaryKey(UsrRegionHometownLink record);
}